language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install blas; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install lapack; fi

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make install
  - make test

  install: true
