version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
platform: x64
matrix:
  - generator: "Visual Studio 15 2017 Win64"
configuration: Release
clone_folder: c:\projects\pnl
build_script:
    - if exist "build" ( rmdir build /s /q )
    - mkdir build
    - cd build
    - cmake -G %generator% ..
    - cmake --build . --config %configuration%
    - cp "src/%configuration%/pnl.dll" "examples/%configuration%"
test_script:
    - ctest --output-on-failure --build-config %configuration%
